/**
 * HeartParticle.jsx
 * ------------------------------------------------------------------
 * Renders a batch of floating ❤️ particles. Each heart is identified
 * by a stable id (generated by the engine) so React can key + animate
 * additions/removals correctly via AnimatePresence.
 * ------------------------------------------------------------------
 */
import { memo } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import styles from './PetCat.module.css';

const HeartParticle = ({ hearts }) => (
  <AnimatePresence>
    {hearts.map((h) => (
      <motion.span
        key={h.id}
        className={styles.heart}
        style={{ left: `calc(50% + ${h.x}px)` }}
        initial={{ opacity: 0, y: 0 }}
        animate={{ opacity: [0, 1, 0], y: -46 }}
        transition={{ duration: 1, ease: 'easeOut' }}
      >
        ❤️
      </motion.span>
    ))}
  </AnimatePresence>
);

export default memo(HeartParticle);
